### ISSUE TITLE
Malfunction with keyboards that send 'Note On' with 0 velocity instead of 'Note Off'

### ISSUE THREAD

**Issue by Moleman0** [la-jarre-a-son/midi-jar#10]
## Expected Behavior

The notes should go off when releasing the keys.

## Current Behavior

The notes show up doubled upon releasing and stay on forever, because the midi message is always Note On.

![Capture](https://user-images.githubusercontent.com/117095206/199035841-9ada4343-70b4-4571-9510-a5c40c3be51a.PNG)

Debug log:
[58496.5730] Axiom 61 MIDI In: channel 1 - 144:Note On - note 48 - 57 
[58667.0615] Axiom 61 MIDI In: channel 1 - 144:Note On - note 48 - 0 
[60075.9404] Axiom 61 MIDI In: channel 1 - 144:Note On - note 50 - 57 
[60208.6306] Axiom 61 MIDI In: channel 1 - 144:Note On - note 50 - 0 
[60919.7518] Axiom 61 MIDI In: channel 1 - 144:Note On - note 52 - 82 
[61023.0185] Axiom 61 MIDI In: channel 1 - 144:Note On - note 52 - 0 
[64152.0226] Axiom 61 MIDI In: channel 1 - 144:Note On - note 53 - 52 
[64264.1501] Axiom 61 MIDI In: channel 1 - 144:Note On - note 53 - 0

## Suggested Solution (if any)

The midi message Note On (0x90) should only be considered to be a note on trigger when its velocity is not 0. Also an 0x90 message with 0 velocity should be equivalent to Note Off (0x80).

Unfortunately this setting cannot be changed in my midi keyboard itself.

## Your Environment

- MIDI Jar version: v1.2.0
- Operating System: Windows 10 Version	10.0.16299 Build 16299
- Hardware Devices: M-Audio Axiom 61 Mk2 through USB, Creative Audigy RX (with native ASIO driver)

**Comment by Moleman0** [comment]
Thank you a lot!

(I read that this is a standard midi functionality called "running status", it requires less data down the line. Normally the status byte needs to be sent with each note twice (0x90 down and 0x80 up), but this way it can stay 0x90 and only the note and velocity values need to be transmitted individually.)

**Comment by mighele** [comment]
Up-vote :) I have this same issue too. Looking forward to a fix. Thanks

**Comment by ArTiSTiX** [comment]
@Moleman0 @mighele 
I updated MIDI Jar to 1.2.1 with a fix.
I don't have any keyboard using this mode so can you notify me if this works for you so that i can close this issue ?

Thanks !

**Comment by mighele** [comment]
I've just tried version 1.2.1 and it now works for me. Thanks for the speedy turn around :)

**Comment by ArTiSTiX** [comment]
Thank you & enjoy !
