### ISSUE TITLE
Support flatpak

### ISSUE THREAD

**Issue by sreich** [la-jarre-a-son/midi-jar#14]
Flatpak seems to be the best and most popular Linux package mechanism, with availability on flathub and such, package managers like those on KDE and thus the steam deck, support flatpak too.

**Comment by ArTiSTiX** [comment]
Since i cannot find any solution with AppImage, i added flatpak as a build target, so maybe you can install it with flatpak.

This does not include publishing to Flathub, i may never publish it on a store.

I simply installed it with ```flatpak install MIDI-Jar-1.5.1-x86_64.flatpak```

Hope this is working well for you too.

**Comment by sreich** [comment]
Yep this is awesome thank you! In kde\archlinux it's just a matter of clicking it and it opens up the Discover software center to install or remove it

It integrates better with the launchers too so thank you for doing this

Not having flathub is fine, I think it would probably help your visibility and people's ability to see it in these ecosystems...I do think that would be very valuable for you, as they should then be searchable inside it

Quite honestly, I've been praising this software in music communities. Your software is awesome, constantly getting great features, free and open source, it's much better than ChordieApp which is the "competitor" that's paid and Windows only (though does work in wine)

I use this app every day in my practice, the web server is really great too because I can either pull it on my desktop or my tablet depending on what I switch to during my practice routine

This has been huge for me to learn chords and theory and understand it all better

You're doing a great thing :) If there's a donation button somewhere I'd love to send some your way

I'm looking forward to the quiz component to getting improvements here too. There's a few things I'd like to see it do there and if you add those I could add those to my daily practice and see my progress accelerate even more again
